import Avatar1 from "../../../../assets/images/users/avatar-1.jpg";
import Avatar2 from "../../../../assets/images/users/avatar-2.jpg";
import Avatar3 from "../../../../assets/images/users/avatar-3.jpg";
import Avatar4 from "../../../../assets/images/users/avatar-4.jpg";
import Avatar5 from "../../../../assets/images/users/avatar-5.jpg";
import Avatar6 from "../../../../assets/images/users/avatar-6.jpg";
import Avatar7 from "../../../../assets/images/users/avatar-7.jpg";
import Avatar8 from "../../../../assets/images/users/avatar-8.jpg";

export const DOCTORS = [
    {
        id: 1,
        name: "Dr. Priya Sharma",
        degree: "BHMS",
        credentials: "BHMS, 10+ Years",
        experience: "6+ Years Experience",
        specialties: "Women's Health, Pediatric",
        specialtiesList: ["Women's Health", "Pediatric", "Fertility"],
        rating: 4.8,
        reviews: 120,
        location: "Bangalore, Karnataka",
        clinicName: "Sharma Homeopathy Clinic",
        clinicAddress: "123 MG Road, Near Metro Station, Bangalore, Karnataka 560001",
        mapsUrl: "https://maps.google.com/?q=MG+Road+Bangalore",
        inClinic: 800,
        tele: 600,
        available: "today",
        image: Avatar2,
        nearby: true,
        mapPos: { top: "22%", left: "36%" },
        distanceKm: 2.4,
        about:
            "Dr. Priya Sharma is a compassionate homeopathy practitioner focused on holistic healing for women and children. She blends classical repertorization with modern case analysis for lasting results. Over the years she has guided hundreds of families through menstrual health concerns, childhood allergies, digestive imbalance, and fertility support with individualized remedies and lifestyle guidance. Patients appreciate her calm listening style, clear follow-up plans, and practical advice that fits busy urban routines. Whether you prefer an in-clinic visit or a tele consultation, she takes time to understand the full case history before recommending a course of treatment.",
        education: "BHMS - Karnataka University",
        specialtyLine: "Specializes in Women's Health, Pediatric, Fertility",
        languages: "Languages: English, Hindi, Kannada",
        timings: {
            weekdays: "10:00 AM - 1:00 PM | 5:00 PM - 8:00 PM",
            sunday: "Closed",
        },
        expertise: [
            "Women's Health",
            "Pediatric",
            "Fertility",
            "Mental Health",
            "Skin",
            "Digestive",
            "Respiratory",
            "Lifestyle Disorders",
        ],
    },
    {
        id: 2,
        name: "Dr. Ananya Mehta",
        degree: "BHMS, MD (Hom)",
        credentials: "BHMS, MD (Hom), 8+ Years",
        experience: "8+ Years Experience",
        specialties: "Skin & Allergy, Hair Fall",
        specialtiesList: ["Skin", "Allergy", "Hair Fall"],
        rating: 4.7,
        reviews: 248,
        location: "Pune, Maharashtra",
        clinicName: "Mehta Homeo Care",
        clinicAddress: "45 FC Road, Shivajinagar, Pune, Maharashtra 411005",
        mapsUrl: "https://maps.google.com/?q=FC+Road+Pune",
        inClinic: 900,
        tele: 700,
        available: "today",
        image: Avatar3,
        about:
            "Dr. Ananya Mehta specializes in chronic skin and allergy cases with a gentle, constitutional approach tailored to each patient's lifestyle and history.",
        education: "BHMS, MD (Hom) - Maharashtra University",
        specialtyLine: "Specializes in Skin, Allergy & Hair Fall",
        languages: "Languages: English, Hindi, Marathi",
        timings: {
            weekdays: "9:30 AM - 1:30 PM | 4:30 PM - 7:30 PM",
            sunday: "Closed",
        },
        expertise: ["Skin", "Allergy", "Hair Fall", "Respiratory", "Digestive", "Pediatric"],
    },
    {
        id: 3,
        name: "Dr. Rohan Desai",
        degree: "BHMS",
        credentials: "BHMS, 12+ Years",
        experience: "12+ Years Experience",
        specialties: "Digestive, Joint Pain",
        specialtiesList: ["Digestive", "Joint Pain"],
        rating: 4.9,
        reviews: 401,
        location: "Mumbai, Maharashtra",
        clinicName: "Desai Homeopathy Centre",
        clinicAddress: "78 Linking Road, Bandra West, Mumbai, Maharashtra 400050",
        mapsUrl: "https://maps.google.com/?q=Linking+Road+Bandra",
        inClinic: 1000,
        tele: 750,
        available: "tomorrow",
        image: Avatar1,
        about:
            "With over a decade of clinical experience, Dr. Rohan Desai helps patients manage digestive and musculoskeletal concerns through precise remedy selection.",
        education: "BHMS - Mumbai University",
        specialtyLine: "Specializes in Digestive & Joint Disorders",
        languages: "Languages: English, Hindi, Gujarati",
        timings: {
            weekdays: "10:00 AM - 2:00 PM | 5:00 PM - 8:00 PM",
            sunday: "Closed",
        },
        expertise: ["Digestive", "Joint Pain", "Lifestyle Disorders", "Respiratory", "Skin"],
    },
    {
        id: 4,
        name: "Dr. Kavita Nair",
        degree: "BHMS",
        credentials: "BHMS, 7+ Years",
        experience: "7+ Years Experience",
        specialties: "Child Health, Cold & Fever",
        specialtiesList: ["Child Health", "Cold & Fever"],
        rating: 4.6,
        reviews: 189,
        location: "Kolhapur, Maharashtra",
        clinicName: "Nair Family Homeopathy",
        clinicAddress: "12 Rankala Road, Kolhapur, Maharashtra 416003",
        mapsUrl: "https://maps.google.com/?q=Rankala+Kolhapur",
        inClinic: 700,
        tele: 550,
        available: "today",
        image: Avatar4,
        nearby: true,
        mapPos: { top: "38%", left: "72%" },
        distanceKm: 1.8,
        about:
            "Dr. Kavita Nair is known for gentle pediatric care and quick relief protocols for seasonal cold, cough and fever in children and adults.",
        education: "BHMS - Shivaji University",
        specialtyLine: "Specializes in Child Health & Acute Care",
        languages: "Languages: English, Hindi, Marathi",
        timings: {
            weekdays: "10:00 AM - 1:00 PM | 5:00 PM - 8:00 PM",
            sunday: "Closed",
        },
        expertise: ["Child Health", "Cold & Fever", "Pediatric", "Respiratory", "Allergy"],
    },
    {
        id: 5,
        name: "Dr. Amit Kulkarni",
        degree: "BHMS",
        credentials: "BHMS, 15+ Years",
        experience: "15+ Years Experience",
        specialties: "Thyroid, Stress & Sleep",
        specialtiesList: ["Thyroid", "Stress", "Sleep"],
        rating: 4.8,
        reviews: 356,
        location: "Nashik, Maharashtra",
        clinicName: "Kulkarni Homeo Clinic",
        clinicAddress: "9 College Road, Nashik, Maharashtra 422005",
        mapsUrl: "https://maps.google.com/?q=College+Road+Nashik",
        inClinic: 1100,
        tele: 800,
        available: "tomorrow",
        image: Avatar5,
        about:
            "Dr. Amit Kulkarni focuses on hormonal balance, thyroid care and stress-related sleep issues with individualized homeopathic treatment plans.",
        education: "BHMS - Pune University",
        specialtyLine: "Specializes in Thyroid, Stress & Sleep",
        languages: "Languages: English, Hindi, Marathi",
        timings: {
            weekdays: "9:00 AM - 1:00 PM | 4:00 PM - 7:00 PM",
            sunday: "Closed",
        },
        expertise: ["Thyroid", "Mental Health", "Lifestyle Disorders", "Women's Health", "Digestive"],
    },
    {
        id: 6,
        name: "Dr. Sneha Patil",
        degree: "BHMS",
        credentials: "BHMS, 9+ Years",
        experience: "9+ Years Experience",
        specialties: "Migraine, Respiratory",
        specialtiesList: ["Migraine", "Respiratory"],
        rating: 4.5,
        reviews: 167,
        location: "Kolhapur, Maharashtra",
        clinicName: "Patil Homeopathy Clinic",
        clinicAddress: "56 Shahupuri, Kolhapur, Maharashtra 416001",
        mapsUrl: "https://maps.google.com/?q=Shahupuri+Kolhapur",
        inClinic: 850,
        tele: 650,
        available: "today",
        image: Avatar6,
        nearby: true,
        mapPos: { top: "68%", left: "28%" },
        distanceKm: 2.7,
        about:
            "Dr. Sneha Patil helps patients find lasting relief from migraine and chronic respiratory complaints using classical homeopathy.",
        education: "BHMS - Shivaji University",
        specialtyLine: "Specializes in Migraine & Respiratory Care",
        languages: "Languages: English, Hindi, Marathi",
        timings: {
            weekdays: "10:00 AM - 1:30 PM | 5:00 PM - 8:00 PM",
            sunday: "Closed",
        },
        expertise: ["Migraine", "Respiratory", "Allergy", "Mental Health", "Lifestyle Disorders"],
    },
    {
        id: 7,
        name: "Dr. Vikram Joshi",
        degree: "BHMS, MD (Hom)",
        credentials: "BHMS, MD (Hom), 11+ Years",
        experience: "11+ Years Experience",
        specialties: "Allergy & Sinus, Skin",
        specialtiesList: ["Allergy", "Sinus", "Skin"],
        rating: 4.7,
        reviews: 274,
        location: "Sangli, Maharashtra",
        clinicName: "Joshi Homeo Hospital",
        clinicAddress: "33 Vishrambag, Sangli, Maharashtra 416415",
        mapsUrl: "https://maps.google.com/?q=Vishrambag+Sangli",
        inClinic: 950,
        tele: 700,
        available: "today",
        image: Avatar7,
        about:
            "Dr. Vikram Joshi treats complex allergy, sinus and skin conditions with evidence-informed homeopathic protocols.",
        education: "BHMS, MD (Hom) - MUHS",
        specialtyLine: "Specializes in Allergy, Sinus & Skin",
        languages: "Languages: English, Hindi, Marathi",
        timings: {
            weekdays: "10:00 AM - 2:00 PM | 5:00 PM - 8:30 PM",
            sunday: "Closed",
        },
        expertise: ["Allergy", "Respiratory", "Skin", "Digestive", "Pediatric"],
    },
    {
        id: 8,
        name: "Dr. Meera Iyer",
        degree: "BHMS",
        credentials: "BHMS, 6+ Years",
        experience: "6+ Years Experience",
        specialties: "Women's Health, Hormonal Issues",
        specialtiesList: ["Women's Health", "Hormonal Issues"],
        rating: 4.6,
        reviews: 142,
        location: "Kolhapur, Maharashtra",
        clinicName: "Iyer Wellness Clinic",
        clinicAddress: "21 Rajarampuri, Kolhapur, Maharashtra 416008",
        mapsUrl: "https://maps.google.com/?q=Rajarampuri+Kolhapur",
        inClinic: 750,
        tele: 580,
        available: "tomorrow",
        image: Avatar8,
        nearby: true,
        mapPos: { top: "74%", left: "64%" },
        distanceKm: 2.1,
        about:
            "Dr. Meera Iyer supports women's hormonal health with personalized homeopathic care for PCOS, fertility and related concerns.",
        education: "BHMS - Shivaji University",
        specialtyLine: "Specializes in Women's Health & Hormonal Issues",
        languages: "Languages: English, Hindi, Tamil",
        timings: {
            weekdays: "10:00 AM - 1:00 PM | 4:30 PM - 7:30 PM",
            sunday: "Closed",
        },
        expertise: ["Women's Health", "Fertility", "Mental Health", "Lifestyle Disorders", "Thyroid"],
    },
];

export const NEARBY_MAP_DOCTORS = [
    ...DOCTORS.filter((doc) => doc.nearby),
    {
        id: 9,
        name: "Dr. Neha Kadam",
        location: "Kolhapur, Maharashtra",
        nearby: true,
        mapPos: { top: "30%", left: "18%" },
        distanceKm: 2.9,
    },
];

export const getDoctorById = (id) =>
    DOCTORS.find((doc) => String(doc.id) === String(id)) || DOCTORS[0];
