export const TERMS_INTRO = {
    html: `<p><b>Homeocentrum ("Homeocentrum ","we","us")</b> provides this web site, associated apps in the AppStore and Play Store and site-related services (collectively, the "Site") subject to your compliance with the terms and conditions set forth in this agreement (the "Agreement"). This Agreement governs the relationship between Homeocentrum and you ("You" and "Your") with respect to your use of the Site. It is important that You read carefully and understand the terms and conditions of this Agreement. <br> We reserve the right at any time to:</p>`,
    list: [
        "Change the terms and conditions of this Agreement;",
        "Change the Site, including eliminating or discontinuing any content on or feature of the Site; or",
        "Change any fees or charges for use of the Site.",
    ],
    after: `<p>Any changes we make will be effective immediately upon notice, which we may provide by means including, without limitation, posting on the Site. Your continued use of the Site after such notice will be deemed acceptance of such changes. Be sure to return to this page periodically to ensure familiarity with the most current version of this Agreement. Upon our request, you agree to sign a non-electronic version of this Agreement.</p>`,
};

export const TERMS_SECTIONS = [
    { title: "1. Registration", html: `<p>You agree to:<br> <b>(a)</b> provide accurate, current and complete information about yourself as prompted by our registration form (including your email address); and <br> <b>(b)</b> maintain and update your information (including your email address) to keep it accurate, current and complete. You acknowledge that, if any information provided by you is untrue, inaccurate, not current or incomplete, we reserve the right to terminate this Agreement and your use of the Site.</p><p>As part of the registration process, you will be asked to input your email address and select a password. You will be responsible for the confidentiality and use of your password and agree not to transfer or resell your use of or access to the Site to any third party. YOU ARE ENTIRELY RESPONSIBLE FOR MAINTAINING THE CONFIDENTIALITY OF YOUR PASSWORD AND FOR ANY AND ALL ACTIVITIES THAT ARE CONDUCTED THROUGH YOUR ACCOUNT. HOMEOCENTRUM SHALL NOT BE LIABLE FOR ANY UNAUTHORISED USE OF YOUR ACCOUNT.</p>` },
    { title: "2. License and Site Access.", html: `<p>Conditioned upon, and subject to, Your compliance with the terms and conditions of this Agreement, Homeocentrum hereby grants You the personal, non-exclusive and non-transferable limited right and license to, during the term of this Agreement, access, install and use, as applicable the Site. Homeocentrum and its licensors reserve all rights not expressly granted to You in this Agreement including, without limitation, all right, title, and other intellectual property rights to the Site. The use of the Site is licensed, not sold.</p>` },
    { title: "3. Respective Subscription Fee", html: `<p>You agree to pay the respective subscription fee that is set forth on the registration page and if you desire to continue accessing the Site, you agree to pay any future subscription fee as established by Homeocentrum from time to time. If you fail to pay the respective subscription fee, then Homeocentrum shall have the right to terminate this Agreement and your use of the Site. No refunds will be made for early termination of the contract prior to the end of the active subscription period(s).</p>` },
    { title: "4. Sensitive Personal Information", html: `<p><b>4.1</b> Homeocentrum may have access through the Site to your Sensitive Personal Information, which includes but is not limited to Your passwords, sexual orientation, financial information such as bank account or credit card or debit card or other payment instrument details, physical, physiological, and mental health conditions, etc.<br><b>4.2</b> Homeocentrum shall be collecting the following Sensitive Personal Information from You for the purpose of allowing your Service Providers, such as doctors, to use the Sensitive Personal Information to provide medical services to You.<br><b>4.3</b> The Sensitive Personal Information that is collected from You will be accessible to the Service Provider and shall be stored until You withdraw Your consent.<br><b>4.4</b> You shall at any time have an option to withdraw Your consent by emailing support@Homeocentrum.com with subject "Withdrawing consent to share information with Homeocentrum".<br><b>4.5</b> In the event that You withdraw your consent, Homeocentrum shall not provide the services for which the said information was sought. Please read Homeocentrum's Privacy Policy for more information.</p>` },
    { title: "5. Payment and Cancellations", html: `<p><b>5.1</b> You agree to pay the subscription fee to Homeocentrum Inc, inclusive of Goods and Services Tax ("GST"), as applicable.<br><b>5.2</b> You alone are responsible for the payments that need to be made towards the services that are being availed of by you.<br><b>5.3</b> You agree to receive SMS/Email Messages from Homeocentrum's service to the mobile phone number/Email provided in the registration form.</p>` },
    { title: "6. Representation and Warranties", html: `<p><b>6.1</b> You represent and warrant that the information that has been provided by You is correct, complete and up to date.<br><b>6.2</b> As has been mandated by law under Rule 3(2) of the Information Technology (Intermediaries Guidelines), 2011, You are hereby prohibited from hosting, displaying, uploading, modifying, publishing, transmitting, updating or sharing any information that violates applicable law.</p>`, list: ["Belongs to another person and to which the user does not have any right to;", "Is grossly harmful, harassing, blasphemous defamatory, obscene, pornographic, or otherwise unlawful;", "Harm minors in any way;", "Infringes any patent, trademark, copyright or other proprietary rights;", "Violates any law for the time being in force;", "Deceives or misleads the addressee;", "Impersonate another person;", "Contains software viruses or any other computer code designed to interrupt, destroy or limit functionality;", "Threatens the unity, integrity, defence, security or sovereignty of India."] },
    { title: "7. Information Provided by Homeocentrum", html: `<p>Although Homeocentrum strives to provide information that is both useful and current, medical research and information changes frequently and is subject to varying interpretations. Accordingly, although Homeocentrum endeavors to use reasonable care in assembling the information, the information may not be up-to-date, accurate or complete, and the information cannot be construed as medical or professional advice on any subject matter. You acknowledge and agree that Homeocentrum shall have no liability for accuracy or applicability of any information that is on the site.</p>` },
    { title: "8. Grievance Officer", html: `<p>In accordance with the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021, if You have any issues with our Site, please get in touch with our Grievance Officer.</p>` },
    { title: "9. Links", html: `<p>The Site may contain links to other Internet web sites which may or may not be owned or operated by Homeocentrum. Homeocentrum has not reviewed all of the web sites that are linked to the Site, and Homeocentrum has no control over such sites. Unless otherwise explicitly stated, Homeocentrum is not responsible for the content of such web sites.</p>` },
    { title: "10. Ownership and Restrictions on Use", html: `<p>The Site is owned and operated by Homeocentrum and the information provided by the Site are and will remain the property of Homeocentrum and are protected by copyright, trademark and other laws. You may not copy, reproduce, republish, upload, post, transmit or distribute any content or information available on or through the Site without our prior written permission.</p>` },
    { title: "11. Termination", html: `<p>This Agreement shall remain effective unless terminated due to: failure to pay subscription fee; breach of any term; illegal, fraudulent or abusive behavior; or acts prejudicial to the interests of Homeocentrum. Upon termination of this Agreement, Your right to use the Site shall immediately cease.</p>` },
    { title: "12. Uptime Guarantee", html: `<p>Homeocentrum will use commercially reasonable efforts to ensure that the site will be available for use at least 95% of the time over each calendar month, available between the hours of 8.00AM and 6.00PM, Indian Standard Time, Monday through Saturday.</p>` },
    { title: "13. Disclaimers", html: `<p>THE SITE, THE MATERIALS ON THE SITE, ANY PRODUCT OR SERVICE OBTAINED THROUGH THE SITE AND THE SOFTWARE ARE PROVIDED "AS IS" AND WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. TO THE FULLEST EXTENT PERMISSIBLE PURSUANT TO APPLICABLE LAW, HOMEOCENTRUM DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED.</p>` },
    { title: "14. Limitation of Liability", html: `<p>NEITHER HOMEOCENTRUM NOR ANY OF OUR AFFILIATES, LICENSORS, SUPPLIERS, ADVERTISERS OR SPONSORS ARE RESPONSIBLE OR LIABLE FOR ANY INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, EXEMPLARY, PUNITIVE OR OTHER DAMAGES ARISING OUT OF OR RELATING IN ANY WAY TO THE SITE.</p>` },
    { title: "15. Indemnification", html: `<p>You agree to indemnify, defend and hold Homeocentrum harmless from and against any and all claims, damages, losses, costs and other expenses that arise directly or indirectly out of or from your breach of this Agreement and/or your activities in connection with the Site.</p>` },
    { title: "16. Cancellation and Refund of Respective Subscription Fee", html: `<p>Homeocentrum does not offer subscription cancellation and no refunds will be made for early termination of the contract prior to the end of the active subscription period(s).</p>` },
    { title: "17. Renewal", html: `<p>You can renew your subscription no earlier than 3 months before it expires. At the end of each subscription period a grace period of 30 calendar days will be given to renew the respective subscription and continue using the Homeocentrum system.</p>` },
    { title: "18. Force Majeure", html: `<p>The duties and obligations of Homeocentrum under this Agreement shall be suspended during such time as the performance by Homeocentrum is prevented or impeded by major riots, civil commotion, rebellion, pestilence, pandemic, Governmental action, war, hostility, acts of God beyond the control of Homeocentrum.</p>` },
    { title: "19. Miscellaneous", html: `<p>If You are residing in India then, this Agreement is governed by and construed in accordance with the laws of India. If any provision of this Agreement is found to be unenforceable, then that provision shall be deemed severable from this Agreement.</p>` },
    { title: "20. Terms Specific to the Republic of India", html: `<p>If You are residing in India, then this Agreement is published in compliance of Indian law, including the Indian Contract Act, 1872; the Information Technology Act, 2000; and related rules. The courts at MUMBAI, MAHARASHTRA shall have the sole jurisdiction. Please read the Homeocentrum Privacy Policy.</p>` },
];
